version: "3.7"

services:
    mongo: 
        image: mongo
        ports:
            - 27017:27017

    back:
        build: FormaSchool-Back
        ports:
            - 8080:8080
        environment: 
            - MONGO_HOST=mongo
            - SERVER_PORT=8080
        depends_on: 
            - mongo
    
    front:
        build: FormaSchool-Front
        ports:
            - 8081:80
